# coding: utf-8

"""
    Kingpick Admin API

    Provides APIs for tenant maintenance

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kingpick_api_client
from kingpick_api_client.rest import ApiException
from kingpick_api_client.apis.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ ProjectApi unit test stubs """

    def setUp(self):
        self.api = kingpick_api_client.apis.project_api.ProjectApi()

    def tearDown(self):
        pass

    def test_create_project(self):
        """
        Test case for create_project

        Creates a new project
        """
        pass

    def test_get_project(self):
        """
        Test case for get_project

        
        """
        pass

    def test_list_projects(self):
        """
        Test case for list_projects

        
        """
        pass

    def test_put_project(self):
        """
        Test case for put_project

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
