# coding: utf-8

"""
    Kingpick Admin API

    Provides APIs for tenant maintenance

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kingpick_api_client
from kingpick_api_client.rest import ApiException
from kingpick_api_client.apis.tenant_api import TenantApi


class TestTenantApi(unittest.TestCase):
    """ TenantApi unit test stubs """

    def setUp(self):
        self.api = kingpick_api_client.apis.tenant_api.TenantApi()

    def tearDown(self):
        pass

    def test_get_tenant(self):
        """
        Test case for get_tenant

        
        """
        pass

    def test_get_tenants(self):
        """
        Test case for get_tenants

        
        """
        pass

    def test_post_tenant(self):
        """
        Test case for post_tenant

        
        """
        pass

    def test_put_tenant(self):
        """
        Test case for put_tenant

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
